<a href="https://colab.research.google.com/github/HebaSedik/machine-learning/blob/master/function_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *
x = fromfunction(lambda i: i**3, (10,))
print(x)

[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]


In [2]:
from numpy import *
x = fromfunction(lambda i: 3 * (i+5)**3, (10,))
print(x)

[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]


In [3]:
from numpy import *
x = fromfunction(lambda i: i**2, (6,))
print(x)

[ 0.  1.  4.  9. 16. 25.]


In [4]:
from numpy import *
x = fromfunction(lambda i,j: i+j, (4,5))
print(x)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]


In [5]:
from numpy import *
x = fromfunction(lambda i,j: 3*i*j, (2,3))
print(x)

[[0. 0. 0.]
 [0. 3. 6.]]


In [6]:
from numpy import *
x = fromfunction(lambda i,j,k: i+j+k, (2,3,4))
print(x)

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]


In [7]:
from numpy import *
x = fromfunction(lambda i,j,k: (2*i)+(j**2)*k, (2,3,4))
print(x)

[[[ 0.  0.  0.  0.]
  [ 0.  1.  2.  3.]
  [ 0.  4.  8. 12.]]

 [[ 2.  2.  2.  2.]
  [ 2.  3.  4.  5.]
  [ 2.  6. 10. 14.]]]


In [8]:
from numpy import *
def powers(i):
    i = i**2
    return i
x = fromfunction(powers, (9,), dtype=int)
print(x)

[ 0  1  4  9 16 25 36 49 64]


In [9]:
from numpy import *
def powers(i,j):
    i = i**j
    return i
x = fromfunction(powers, (4,5), dtype=int)
print(x)

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]


In [10]:
from numpy import *
m,n = 20, 5
def f(i):
    return (i % n == 0)
x = fromfunction(f, (m,), dtype=int)
print(x)

[ True False False False False  True False False False False  True False
 False False False  True False False False False]
