<a href="https://colab.research.google.com/github/HebaSedik/machine-learning/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from  numpy import *
a = sin(30)
b = cos(30)
c = tan(30)
print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [ ]:
import numpy as np
a = np.sin(30)
b = np.cos(30)
c = np.tan(30)
print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [ ]:
from  numpy import *

a = sin(30*np.pi/180)
b = cos(30*np.pi/180)
c = tan(30*np.pi/180)
print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [ ]:
from  numpy import *
a = sin(deg2rad(30))
b = cos(deg2rad(30))
c = tan(deg2rad(30))
print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [ ]:
from  numpy import *
a = round(3.68528)
b = round(3.68528,1)
c = round(3.68528,2)
d = round(3.68528,3)
e = round(3.68528,4)
print(a)
print(b)
print(c)
print(d)
print(e)

4
3.7
3.69
3.685
3.6853


In [ ]:
from  numpy import *
a = floor(3.68528)
b = ceil(3.68528)
print(a)
print(b)

3.0
4.0


In [ ]:
from  numpy import *
a = mod(20,7)
b = power(2,5)
print(a)
print(b)

6
32


In [ ]:
from  numpy import *
a = [2,3,6,5,4,7,8]
b = array(a)
print(a)
print(b)

[2, 3, 6, 5, 4, 7, 8]
[2 3 6 5 4 7 8]


In [ ]:
from  numpy import *
a = [[1,2,3],[5,3,6],[9,6,5]]
b = array(a)
print(a)
print(b)

[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [ ]:
import numpy as np
ps = [1,2,3,4] #array_one_dim
ls = [[1,2,3,4],[5,6,7,8]] # array_two_dim
array = np.array(ps)
array1 = np.array(ls)
print(ls)
print(ps)
print(array)
print(array1)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[1, 2, 3, 4]
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#طباعه مجموعه ارقام
import numpy as np
arange =np.arange(1,10) #طباعه ارقام
print(arange)
arange =np.arange(1,10,3)# طباعه ارقام بس هيمشي 3 خطوات مش 1 زي الاول
print(arange)


[1 2 3 4 5 6 7 8 9]
[1 4 7]


In [ ]:
from  numpy import *
a = array([range(i, i + 3) for i in [2, 4, 6]])
print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
from  numpy import *
a = array([('x',3,4.2),('y',4,5.3),('z',5,6.3)],
           dtype =[('name','U5'),('number','i2'),
                 ('value','f4')])
print(a)

[('x', 3, 4.2) ('y', 4, 5.3) ('z', 5, 6.3)]


In [ ]:
from  numpy import *
a = empty((3,2))
print(a)

[[4.71047433e-310 0.00000000e+000]
 [6.80672722e-310 6.80672723e-310]
 [6.80672723e-310 6.80673942e-310]]


In [ ]:
#عمل مصفوفه صفريه
import numpy as np
z = np.zeros(4) # عمل مصفوفه مكونه من اصفار فقط
z = np.zeros((4,4)) #عمل مصفوفه صفريه 4 *4
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#عمل مصفوفه مكونه من 1 فقط
import numpy as np
z = np.ones(4) # عمل مصفوفه مكونه من واحد فقط
z = np.ones((4,4))
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
from numpy import *
a = random.uniform(1,10)
b = random.uniform(1,10,20)
print(a)
print('-------------------------')
print(b)
print('-------------------------')

8.913482515323158
-------------------------
[5.21113536 2.58002602 7.15289203 3.34411524 9.53063536 8.79920375
 5.11306295 2.47455809 1.34430953 8.44803388 8.11509584 3.9200516
 8.05833607 3.0641126  6.62126823 3.18140951 9.1973115  4.12605448
 1.91172267 4.93599811]
-------------------------


In [ ]:
# اظهار مجموعه ارقام عشوائيه
import numpy as np
r = np.random.rand(5) #بتطلع ارقام عشوائيه بين 0 و 1
r = np.random.rand(5,4) #عمل مصفوفه
r = np.random.randint(100) #بتطلع ارقام عشوائيه صحيحه
r = np.random.randint(100,200) #ارقام صحيحه بين الرقمين دول
r = np.random.randint(100,200,5) #بيطلع 5 ارقام بين 100 و 200
r = np.random.randint(100,200,(5,2)) #ارقام عشوائيه علي هيئه مصفوفه
r = np.random.randint(100,200,20) #بتطلع ارقام عشوائيه صحيحه
shape = r.reshape(5,4) #بتعيد تشكيل الارقام ولازم الارقام بتاع المصفوفه تنفع مع رقم العناصر ال عايز اعرضها زي ال 20 ال فوق دي
print (r)


[171 129 190 160 138 195 115 129 163 107 167 190 112 104 190 105 139 178
 194 139]


In [ ]:
from  numpy import *
a =random.random((2,3))
print(a)

[[0.84542952 0.69587948 0.42549953]
 [0.16660351 0.51501758 0.802942  ]]


In [ ]:
from  numpy import *
a =random.normal(0,1,10)
print(a)

[ 0.93549405  0.58596847  0.89367818 -0.05955106 -0.12102119 -0.67548379
  0.99185209 -1.01063372 -0.53467999  0.33791216]


In [ ]:
#الغبط الارقام
import numpy as np
numbers =np.arange(1,10)
print(numbers)
np.random.shuffle(numbers)
print('\n')
print(numbers)

[1 2 3 4 5 6 7 8 9]


[7 5 9 1 3 8 2 6 4]


In [ ]:
#الغبط مصفوفه بطريقه عشوائيه
import numpy as np
numbers =np.arange(1,13)
numbers_reshaped = numbers.reshape(3,4)
print(numbers_reshaped )
np.random.shuffle(numbers_reshaped )
print('\n')
print(numbers_reshaped )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
from  numpy import *
a =  random.randint(150)
print(a)

11


In [ ]:
from  numpy import *
a =random.randint(5, size=7)
print(a)

[1 3 3 0 1 3 1]


In [ ]:
from  numpy import *
a =random.randint(5,20, size=7)
print(a)

[11  6  9  5 17 18 10]


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
print(a)

[[0 7 8]
 [1 8 6]
 [1 5 5]]


In [ ]:
from  numpy import *
a = random.randint(5,10, size=(3, 4, 5))
print(a)

[[[6 5 5 8 6]
  [5 8 8 7 7]
  [7 7 8 5 6]
  [6 6 8 7 9]]

 [[6 8 9 8 9]
  [9 6 7 9 6]
  [7 5 9 9 7]
  [6 6 7 9 6]]

 [[9 9 7 9 7]
  [8 5 6 6 8]
  [8 9 9 8 9]
  [5 5 7 6 9]]]


In [ ]:
from  numpy import *
a = random.randint(1,60,25)
b = reshape(a,(5,5))
print(a)
print(b)

[19 52  1  4 35 24 24 18 17 51 49 47 38 21 34 12 43 53 32 47 16 53 57 58
 17]
[[19 52  1  4 35]
 [24 24 18 17 51]
 [49 47 38 21 34]
 [12 43 53 32 47]
 [16 53 57 58 17]]


In [ ]:
from  numpy import *
a = random.rand(15)
print(a)

[0.72006351 0.54344737 0.29250937 0.55665656 0.52037287 0.68006913
 0.26365458 0.15521971 0.128329   0.9899497  0.53235708 0.31245084
 0.68032446 0.36820459 0.55884386]


In [ ]:
#معرفه تفاصيل عن المصفوفه اكبر رقم
import numpy as np
numbers =np.random.randint(1,10,(5,5))
print(numbers)
maximuim = numbers.max()
print ("max :" +str(maximuim))

[[8 7 6 8 5]
 [8 6 4 5 9]
 [9 9 7 1 5]
 [9 1 8 4 1]
 [7 2 2 8 2]]
max :9


In [ ]:
#معرفه اصغر رقم ف المصفوفه
import numpy as np
numbers =np.random.randint(1,10,(5,5))
print(numbers)
minmuim = numbers.min()
print ("min :" +str(minmuim))

[[4 1 8 4 1]
 [5 7 1 3 4]
 [1 1 2 9 4]
 [8 9 3 5 5]
 [6 2 7 2 5]]
min :1


In [ ]:
#معرفه مكان اكبر index
import numpy as np
numbers =np.random.randint(1,20,(5,5))
print(numbers)
max_index = numbers.argmax()
print ("max index :" +str(max_index))

[[11 11  8 16  5]
 [ 6 17  4 15 12]
 [15 16  7  5  9]
 [17 11 10  4  3]
 [ 5 16 18  3  8]]
max index :22


In [ ]:
#معرفه ابعاد المصفوفه
import numpy as np
numbers =np.random.randint(1,20,(5,5))
print(numbers)
shape = numbers.shape
print ("shape :" +str(shape))

[[ 2  9 19  1  7]
 [13 11 17 19 13]
 [ 2  1  1 17 13]
 [ 5  6  9 16  6]
 [17 11 11 12  6]]
shape :(5, 5)


In [ ]:
#معرفه عدد الصفوف
import numpy as np
numbers =np.random.randint(1,20,(5,6))
print(numbers)
shape = numbers.shape[0]
print ("shape :" +str(shape))

[[ 6  6  4  8  7  6]
 [ 2 16  1 13  6  1]
 [19  7 12 17 18 17]
 [12  1 10 15 10 14]
 [ 7  9 14 10 15  1]]
shape :5


In [ ]:
#معرفه عدد الاعمده
import numpy as np
numbers =np.random.randint(1,20,(5,6))
print(numbers)
shape = numbers.shape[1]
print ("shape :" +str(shape))

[[19 17  9 13 16  3]
 [ 6  4 17 12 14  3]
 [11 14 19  8  1 18]
 [17 15  8  3 14  8]
 [18  9  1  1  1 10]]
shape :6


In [ ]:
#تقريب الارقام بدل الكسور لاعلي رقم
import numpy as np
numbers =np.ceil(2.3)
print(numbers)

3.0


In [ ]:
#تقريب الارقام لاقل رقم
import numpy as np
numbers =np.floor(2.3)
print(numbers)#

2.0


In [ ]:
#تقريب الارقام علي حسب قيمه الكسر
import numpy as np
numbers1 =np.round(2.3)
numbers2 =np.round(2.6)
print(numbers1)
print(numbers2)

2.0
3.0


In [ ]:
#داله جمع
import numpy as np
numbers =np.add(2,3)
print(numbers)

5


In [ ]:
#جمع مصفوفه ورقم
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
add = np.add(matrix,2)
print(add)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#جمع اتنين مصفوفه
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.add(matrix1,matrix2)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#داله ضرب
import numpy as np
add = np.multiply(3,3)
print(add)

9


In [ ]:
#ضرب رقم في مصفوفه
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
add = np.multiply(matrix,2)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#ضرب مصفوفتين
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.multiply(matrix1,matrix2)
print(add)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
#قسمه مصفوفتين
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.divide(matrix1,matrix2)
print(add)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from  numpy import *
a = random.rand(5,3)
print(a)

[[0.40646935 0.40620151 0.68318463]
 [0.55633579 0.65471846 0.59813162]
 [0.31835369 0.65610904 0.09796584]
 [0.81177524 0.88699211 0.8226763 ]
 [0.42082356 0.03201774 0.45689459]]


In [ ]:
from  numpy import *
a = random.rand(5,3,2)
print(a)

[[[0.30807938 0.8344608 ]
  [0.68843025 0.76976713]
  [0.53736134 0.12558989]]

 [[0.85591543 0.4165844 ]
  [0.49694534 0.85045608]
  [0.64071717 0.60040674]]

 [[0.76397239 0.27041011]
  [0.86969883 0.81787571]
  [0.45818415 0.51297765]]

 [[0.32116707 0.52233005]
  [0.77882346 0.08351169]
  [0.53484302 0.57365038]]

 [[0.69547389 0.36897192]
  [0.03506817 0.90306588]
  [0.67741889 0.30856499]]]


In [ ]:
from  numpy import *
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)
print(a)

6


In [ ]:
from  numpy import *
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y, size = 5)
print(a)

[5 8 8 2 7]


In [ ]:
from  numpy import *
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print(y)
random.shuffle(y)
print(y)

[1, 2, 3, 6, 9, 8, 5, 4, 7, 8, 9, 6, 5, 9, 6]
[4, 5, 8, 9, 9, 3, 5, 1, 7, 6, 8, 9, 6, 2, 6]


In [ ]:
from  numpy import *
a = zeros(8)
b = ones(10)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
from  numpy import *
a = zeros((2,3,2))
b = ones((2,3,2))
print(a)
print(b)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
from  numpy import *
a = eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
from  numpy import *
a = full((3, 5), 35)
print(a)

[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]


In [ ]:
from  numpy import *
a =arange(18).reshape(3,6)
b =arange(27).reshape(3,3,3)
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
from  numpy import *
b =linspace(0,30)
c =linspace(0,100,5)
print(b)
print(c)

[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
[  0.  25.  50.  75. 100.]


In [ ]:
from  numpy import *
b =linspace(0,30,12).reshape(3,4)
c =linspace(0,100,27).reshape(3,3,3)
print(b)
print(c)

[[ 0.          2.72727273  5.45454545  8.18181818]
 [10.90909091 13.63636364 16.36363636 19.09090909]
 [21.81818182 24.54545455 27.27272727 30.        ]]
[[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462  38.46153846  42.30769231]
  [ 46.15384615  50.          53.84615385]
  [ 57.69230769  61.53846154  65.38461538]]

 [[ 69.23076923  73.07692308  76.92307692]
  [ 80.76923077  84.61538462  88.46153846]
  [ 92.30769231  96.15384615 100.        ]]]


In [ ]:
from numpy import *
a =diag(array([5,12,4,-1,3]))
b =diag(array([5,12,4,-1,3]),k=3)
print(a)
print('-------------------------')
print(b)
print('-------------------------')

[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
-------------------------


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a)
print(a)
print(b)

[[5 7 9]
 [3 7 7]
 [5 8 8]]
9


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5)
c = count_nonzero(a<8)
print(a)
print(b)
print(c)

[[5 5 2]
 [5 8 4]
 [3 3 7]]
2
8


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5,axis=1)
c = count_nonzero(a<8,axis=1)
print(a)
print(b)
print(c)

[[9 4 2]
 [0 6 7]
 [9 2 5]]
[1 2 1]
[2 3 2]


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = any(a>5)
print(a)
print(b)

[[7 0 4]
 [2 1 1]
 [5 9 7]]
True


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = any(a>5,axis=1)
print(a)
print(b)

[[7 6 0]
 [8 6 1]
 [1 4 7]]
[ True  True  True]


In [ ]:
from  numpy import *
a = random.randint(0, 10, (3, 3))
b = all(a>5)
print(a)
print(b)

[[0 4 2]
 [2 8 1]
 [0 4 9]]
False


In [ ]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b = a>10
c = a<15
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[ 6 11  7]
 [11 11 10]
 [ 9 11 18]]
-------------------------
[[False  True False]
 [ True  True False]
 [False  True  True]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]


In [ ]:
from  numpy import *
a =arange(9).reshape(3,3)
b =arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)
e = isclose(a,c,rtol = 0.1)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------------
[[ True False False]
 [False False False]
 [False False False]]


In [ ]:
from  numpy import *
a =arange(5)
b =empty(5)
multiply(a, 10, out=b)
print(a)
print(b)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [ ]:
from  numpy import *
a =arange(5)
b =empty(5)
power(a, 4, out=b)
print(a)
print(b)

[0 1 2 3 4]
[  0.   1.  16.  81. 256.]


In [ ]:
from  numpy import *
a =arange(15)
b = add.reduce(a)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105


In [ ]:
from  numpy import *
a =arange(2,8)
b = multiply.reduce(a)
print(a)
print(b)

[2 3 4 5 6 7]
5040


In [ ]:
from  numpy import *
a =arange(2,8)
b = multiply.outer(a,a)
print(a)
print(b)

[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


In [ ]:
from  numpy import *
a =arange(10)
b = add.accumulate(a)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [ ]:
from  numpy import *
a =arange(2,8)
b = multiply.accumulate(a)
print(a)
print(b)

[2 3 4 5 6 7]
[   2    6   24  120  720 5040]


In [ ]:
from  numpy import *
a =arange(12)
b = len(a)
c = a.reshape(3,4)
d = len(c)
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3


In [ ]:
from  numpy import *
a =arange(12)
b = a.size
c = a.reshape(3,4)
d = c.size
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


In [ ]:
from  numpy import *
a =arange(12)
b = a.shape
c = a.reshape(3,4)
d = c.shape
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
from  numpy import *
a =arange(12)
b = a.ndim
c = a.reshape(3,4)
d = c.ndim
print("a",a)
print('b',b)
print('c',c)
print('d',d)

a [ 0  1  2  3  4  5  6  7  8  9 10 11]
b 1
c [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
d 2


In [ ]:
from  numpy import *
a =array(['a','d','g','h','j'])
b = a.dtype
c = arange(12)
d = c.reshape(3,4)
e = d.dtype
print("a",a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a ['a' 'd' 'g' 'h' 'j']
b <U1
c [ 0  1  2  3  4  5  6  7  8  9 10 11]
d [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
e int64


In [ ]:
from  numpy import *
a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


In [ ]:
from  numpy import *
a =arange(9)
b = a.reshape(3,3)
c = trace(b)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [ ]:
from  numpy import *
a =arange(9)
b = a.reshape(3,3)
c = linalg.det(b)
d = linalg.eig(b)
print('a',a)
print('b',b)
print('c',c)
print('d',d)

a [0 1 2 3 4 5 6 7 8]
b [[0 1 2]
 [3 4 5]
 [6 7 8]]
c 0.0
d (array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [ ]:
from  numpy import *
a =arange(10)
c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]
print('a',a)
print('c',c)
print('d',d)
print('e',e)
print('f',f)
print('g',g)

a [0 1 2 3 4 5 6 7 8 9]
c 3
d [3 4 5 6 7 8]
e [3 5 7]
f 9
g 7


In [ ]:
from  numpy import *
a =arange(36).reshape(6,6)
c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


In [ ]:
from  numpy import *
a =arange(36).reshape(6,6)
c = a[3,1]
d = a[3,:]
e = a[:,2]
f = a[:,1:3]
g = a[1:2,:]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [ ]:
from  numpy import *
a =arange(36).reshape(6,6)
c = a[::2,::3]
d = a[::-1,::-1]
e = a[:2:-1,:3:-1]
f = a[2::2,3::3]
g = a[-1::,-1::]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[ 0  3]
 [12 15]
 [24 27]]
-------------------------
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
-------------------------
[[35 34]
 [29 28]
 [23 22]]
-------------------------
[[15]
 [27]]
-------------------------
[[35]]


In [ ]:
from  numpy import *
a =arange(16).reshape(4,4)
print(a)
a[2,3] = 0
print(a)
a[:,3] = 0
print(a)
a[2,:] = 0
print(a)
a[:,:] = 0
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
from  numpy import *
a =arange(16).reshape(4,4)
print(a)
b = a[:,1:3]
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [ ]:
from  numpy import *
a =arange(16).reshape(4,4)
print(a)
b = a[:,1:3].copy()
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [ ]:
from  numpy import *
a =arange(18).reshape(3,3,2)
c = a[1]
d = a[1,2]
e = a[2,2,1]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
-------------------------
[[ 6  7]
 [ 8  9]
 [10 11]]
-------------------------
[10 11]
-------------------------
17


In [ ]:
from  numpy import *
x = [11,22,33,44,55,66,77,88]
x1, x2, x3 = split(x, (3,6))
print(x1, x2, x3)
x1, x2, x3 = split(x, (1,5))
print(x1, x2, x3)
x1, x2, x3 = split(x, (6, 3))
print(x1, x2, x3)
x1, x2, x3 = split(x, (0, 3))
print(x1, x2, x3)
x1, x2, x3 = split(x, (4, 0))
print(x1, x2, x3)

[11 22 33] [44 55 66] [77 88]
[11] [22 33 44 55] [66 77 88]
[11 22 33 44 55 66] [] [44 55 66 77 88]
[] [11 22 33] [44 55 66 77 88]
[11 22 33 44] [] [11 22 33 44 55 66 77 88]


In [ ]:
from  numpy import *
a =arange(16).reshape(4,4)
b = a[2][1]
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
9


In [ ]:
from  numpy import *
a =arange(4).reshape(2,2)
b =2*arange(4).reshape(2,2)
c = vstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [ ]:
from  numpy import *
a =arange(4).reshape(2,2)
b =2*arange(4).reshape(2,2)
c = hstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1 0 2]
 [2 3 4 6]]


In [ ]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 0)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[16  6 18]
 [10  6 19]
 [11  7 13]]
-------------------------
[[11  9  7]
 [11  9  9]
 [ 8 16 14]]
-------------------------
[[16  6 18]
 [10  6 19]
 [11  7 13]
 [11  9  7]
 [11  9  9]
 [ 8 16 14]]
-------------------------


In [ ]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 1)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[ 7 19  6]
 [ 5 15 19]
 [ 8 15 15]]
-------------------------
[[13  5 18]
 [15  8  9]
 [17 10  7]]
-------------------------
[[ 7 19  6 13  5 18]
 [ 5 15 19 15  8  9]
 [ 8 15 15 17 10  7]]
-------------------------


In [ ]:
import numpy as np
a =np.random.randint(5,20, size=9).reshape(3,3)
b = np.max(a)
c = np.min(a)
d = np.argmax(a)
e = np.argmin(a)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[ 9 12 15]
 [10 12  9]
 [ 5  7 18]]
-------------------------
18
-------------------------
5
-------------------------
8
-------------------------
6


In [ ]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b = var(a)
c = cov(a)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[19 19 14]
 [17  5  8]
 [14 18  7]]
-------------------------
26.469135802469136
-------------------------
[[ 8.33333333  5.         15.        ]
 [ 5.         39.         -3.        ]
 [15.         -3.         31.        ]]
