<a href="https://colab.research.google.com/github/HebaSedik/machine-learning/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
ps = [1,2,3,4] #array_one_dim
ls = [[1,2,3,4],[5,6,7,8]] # array_two_dim
array = np.array(ps)
array1 = np.array(ls)
print(ls)
print(ps)
print(array)
print(array1)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[1, 2, 3, 4]
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
#طباعه مجموعه ارقام
import numpy as np
arange =np.arange(1,10) #طباعه ارقام
print(arange)
arange =np.arange(1,10,3)# طباعه ارقام بس هيمشي 3 خطوات مش 1 زي الاول
print(arange)


[1 2 3 4 5 6 7 8 9]
[1 4 7]


In [4]:
#عمل مصفوفه صفريه
import numpy as np
z = np.zeros(4) # عمل مصفوفه مكونه من اصفار فقط
z = np.zeros((4,4)) #عمل مصفوفه صفريه 4 *4
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#عمل مصفوفه مكونه من 1 فقط
import numpy as np
z = np.ones(4) # عمل مصفوفه مكونه من واحد فقط
z = np.ones((4,4))
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# اظهار مجموعه ارقام عشوائيه
import numpy as np
r = np.random.rand(5) #بتطلع ارقام عشوائيه بين 0 و 1
r = np.random.rand(5,4) #عمل مصفوفه
r = np.random.randint(100) #بتطلع ارقام عشوائيه صحيحه
r = np.random.randint(100,200) #ارقام صحيحه بين الرقمين دول
r = np.random.randint(100,200,5) #بيطلع 5 ارقام بين 100 و 200
r = np.random.randint(100,200,(5,2)) #ارقام عشوائيه علي هيئه مصفوفه
r = np.random.randint(100,200,20) #بتطلع ارقام عشوائيه صحيحه
shape = r.reshape(5,4) #بتعيد تشكيل الارقام ولازم الارقام بتاع المصفوفه تنفع مع رقم العناصر ال عايز اعرضها زي ال 20 ال فوق دي
print (r)


[114 132 178 185 162 191 118 161 193 144 116 156 172 198 170 153 179 185
 164 133]


In [7]:
#الغبط الارقام
import numpy as np
numbers =np.arange(1,10)
print(numbers)
np.random.shuffle(numbers)
print('\n')
print(numbers)

[1 2 3 4 5 6 7 8 9]


[9 3 1 4 8 5 7 2 6]


In [8]:
#الغبط مصفوفه بطريقه عشوائيه
import numpy as np
numbers =np.arange(1,13)
numbers_reshaped = numbers.reshape(3,4)
print(numbers_reshaped )
np.random.shuffle(numbers_reshaped )
print('\n')
print(numbers_reshaped )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [9]:
#معرفه تفاصيل عن المصفوفه اكبر رقم
import numpy as np
numbers =np.random.randint(1,10,(5,5))
print(numbers)
maximuim = numbers.max()
print ("max :" +str(maximuim))

[[1 4 4 2 1]
 [3 8 3 4 8]
 [1 8 7 4 8]
 [8 8 8 4 3]
 [3 9 2 1 7]]
max :9


In [10]:
#معرفه اصغر رقم ف المصفوفه
import numpy as np
numbers =np.random.randint(1,10,(5,5))
print(numbers)
minmuim = numbers.min()
print ("min :" +str(minmuim))

[[5 9 2 8 1]
 [3 3 4 6 1]
 [6 7 3 8 1]
 [6 4 5 3 3]
 [6 3 1 5 7]]
min :1


In [11]:
#معرفه مكان اكبر index
import numpy as np
numbers =np.random.randint(1,20,(5,5))
print(numbers)
max_index = numbers.argmax()
print ("max index :" +str(max_index))

[[16 11 12  1 18]
 [11 14 14  3  3]
 [15  5  1  8 10]
 [ 5  7 17 15 12]
 [14  9  5 17  3]]
max index :4


In [12]:
#معرفه ابعاد المصفوفه
import numpy as np
numbers =np.random.randint(1,20,(5,5))
print(numbers)
shape = numbers.shape
print ("shape :" +str(shape))

[[ 3 12 18  9  4]
 [10 13 19  9 11]
 [ 4  4 11  6 10]
 [ 9  5 17  9 19]
 [18 15 14 12 16]]
shape :(5, 5)


In [13]:
#معرفه عدد الصفوف
import numpy as np
numbers =np.random.randint(1,20,(5,6))
print(numbers)
shape = numbers.shape[0]
print ("shape :" +str(shape))

[[19 16  8  4  8  5]
 [ 7 14 17  2  6  5]
 [ 6 17 15 11 10  9]
 [ 8 18 16  7  9 17]
 [ 4  7  6  4 11 10]]
shape :5


In [14]:
#معرفه عدد الاعمده
import numpy as np
numbers =np.random.randint(1,20,(5,6))
print(numbers)
shape = numbers.shape[1]
print ("shape :" +str(shape))

[[ 5  6  3 10 10  5]
 [10  8  7 19 11 13]
 [ 5  1 15  6  3  2]
 [ 9 14  3  4 17 19]
 [ 1 18 15  5 14  5]]
shape :6


In [15]:
#تقريب الارقام بدل الكسور لاعلي رقم
import numpy as np
numbers =np.ceil(2.3)
print(numbers)

3.0


In [16]:
#تقريب الارقام لاقل رقم
import numpy as np
numbers =np.floor(2.3)
print(numbers)#

2.0


In [17]:
#تقريب الارقام علي حسب قيمه الكسر
import numpy as np
numbers1 =np.round(2.3)
numbers2 =np.round(2.6)
print(numbers1)
print(numbers2)

2.0
3.0


In [18]:
#داله جمع
import numpy as np
numbers =np.add(2,3)
print(numbers)

5


In [19]:
#جمع مصفوفه ورقم
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
add = np.add(matrix,2)
print(add)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
#جمع اتنين مصفوفه
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.add(matrix1,matrix2)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [21]:
#داله ضرب
import numpy as np
add = np.multiply(3,3)
print(add)

9


In [22]:
#ضرب رقم في مصفوفه
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
add = np.multiply(matrix,2)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
#ضرب مصفوفتين
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.multiply(matrix1,matrix2)
print(add)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [24]:
#قسمه مصفوفتين
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]
add = np.divide(matrix1,matrix2)
print(add)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
